### ISSUE TITLE
Error occurred. SeqPlots will terminate.

### ISSUE THREAD

**Issue by arabihetero** [Przemol/seqplots#15]
Error occurred. SeqPlots will terminate. I got. error in statement is no such table:files.

**Comment by Ole2016** [comment]
Same for me. I got this Error: 
Error occurred. SeqPlots will terminate.
Please investigate *details* on SeqPlots diagnostic window for more information. Last error message:

error in statement: no such table: files

Loading application...
PROGRESS:10
Copying demo files and genomes...
PROGRESS:15
Lade n"otiges Paket: DBI
Lade n"otiges Paket: methods
Error in sqliteSendQuery(con, statement, bind.data) : 
  error in statement: no such table: files

**Comment by Przemol** [comment]
Hi arabihetero and Ole2016 ,

Thanks for feedback. I have discontinued an old macOS package in favor of new, stand-alone implementation, that supports more operating systems. Installing it should solve the issue.

You can find the software here: https://github.com/Przemol/seqplots_electron/releases/latest, and the installation instructions here: http://przemol.github.io/seqplots/#installation---app-for-mac-win-and-linux

Please start a new issue if you find the same or any other problems with new version.
