### ISSUE TITLE
Problems about normalization between datasets for profile plot

### ISSUE THREAD

**Issue by pengyu1608** [Przemol/seqplots#16]
I drawed profile plot for five datasets. The inputed bigWig file were created by HOMER and total tag counts were normalized to 1e7. In the profile plot, I noticed the baseline of 5 datasets were quite different (see below). I wonder how the normalization within SeqPlots is done?
![testprofileplot](https://cloud.githubusercontent.com/assets/21189327/18236502/3bedc03e-7359-11e6-9ba0-a35beac71a8e.png)

**Comment by Przemol** [comment]
Hi pengyu1608,

SeqPlots does not normalize the signal by default and plots values directly obtained from track file.
However, you can use `Transform signal` option in `Guide lines and data scaling` tab to log2 transform or z-score (the mean and standard deviation are calculated based only on plotting ranges, not the whole track) your signal. z-score transform would make the baselines match on the plot.

**Comment by pengyu1608** [comment]
Thanks for the explanation.

Best,
Peng



yup@pku.edu.cn
 
From: Przemol
Date: 2016-10-31 20:24
To: Przemol/seqplots
CC: Peng Yu; Author
Subject: Re: [Przemol/seqplots] Problems about normalization between datasets for profile plot (#16)
Hi pengyu1608,
SeqPlots does not normalize the signal by default and plots values directly obtained from track file.
However, you can use Transform signal option in Guide lines and data scaling tab to log2 transform or z-score (the mean and standard deviation are calculated based only on plotting ranges, not the whole track) your signal. z-score transform would make the baselines match on the plot.

**Comment by pengyu1608** [comment]
Hi, Przemol:

I have a question about clustering part of seqplots. Could it be possible to export the clustering result (i.e. relationship of genes to cluster)? It will be very helpful. Thanks.


 
From: Przemol
Date: 2016-10-31 20:24
To: Przemol/seqplots
CC: Peng Yu; Author
Subject: Re: [Przemol/seqplots] Problems about normalization between datasets for profile plot (#16)
Hi pengyu1608,
SeqPlots does not normalize the signal by default and plots values directly obtained from track file.
However, you can use Transform signal option in Guide lines and data scaling tab to log2 transform or z-score (the mean and standard deviation are calculated based only on plotting ranges, not the whole track) your signal. z-score transform would make the baselines match on the plot.

**Comment by Przemol** [comment]
Just click "Cluster indicates" in the bottom left. Hore on the clustering result here: http://przemol.github.io/seqplots/#getting-pdfs-and-cluster-info
![image](https://cloud.githubusercontent.com/assets/910537/19893974/24cbab52-a043-11e6-9f51-6bfdfcb7f027.png)
> ![image](https://cloud.githubusercontent.com/assets/910537/19894039/593bf84c-a043-11e6-9a32-5bced0a3f19d.png)
