### ISSUE TITLE
Error with MacOS Package

### ISSUE THREAD

**Issue by chenyu325** [Przemol/seqplots#17]
I can run seqplots using R. But I get the following error when using the MacOS package. Thanks.

c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'htmltools' 0.3 is already loaded, but >= 0.3.5 is required
In addition: Warning messages:
1: package 'methods' was built under R version 3.2.3 
2: package 'BiocGenerics' was built under R version 3.2.2 
3: package 'parallel' was built under R version 3.2.3 
4: package 'stats4' was built under R version 3.2.3 
5: package 'shiny' was built under R version 3.2.3 
Error : package or namespace load failed for 'seqplots'

**Comment by Przemol** [comment]
Hi chenyu325,

Thanks for feedback. I have discontinued an old macOS package in favor of new, stand-alone implementation, that supports more operating systems. Installing it should solve the issue.

You can find the software here: https://github.com/Przemol/seqplots_electron/releases/latest, and the installation instructions here: http://przemol.github.io/seqplots/#installation---app-for-mac-win-and-linux

Please start a new issue if you find the same or any other problems with new version.
