### ISSUE TITLE
Unknown genome name/genome not installed

### ISSUE THREAD

**Issue by munkitchoy** [Przemol/seqplots#19]
I keep getting "Unknown genome name/genome not installed! Use UCSC compatible or contact administrator" error when uploading files. I did install the genome (HG19) in R.

**Comment by Przemol** [comment]
Hi munkitchoy, 

Thanks for feedback. I was getting similar error under certain conditions. This issue should be fixed in 6cd0d1952861e5cf09f29d17833db7fa7a125690. Just install newest development version by following code:

```
if (!require("devtools")) install.packages("devtools")
devtools::install_github('przemol/seqplots', build_vignettes=FALSE)
```

Please let me know if this does not help.
