### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by jawmajewski** [Przemol/seqplots#21]
Hi, 

Great tool and a lot of fun to play with. Could you add an option to normalize by total tags? Right now it is very difficult to compare profiles from different size datasets (and the Z-score normalization does not really help)

J

**Comment by Przemol** [comment]
The BW tracks need to be normalised by external software.

For BAM it's theoretically possible to include such option, but I would still recommend using specialised software, like rBEADS:
https://github.com/Przemol/rbeads

 It does a proper normalisation, in addition to sequencing depth balancing.
