### ISSUE TITLE
Shiny server setup: Seqplots returns "Disconnected from server"

### ISSUE THREAD

**Issue by khourhin** [Przemol/seqplots#22]
Hello,

I want to setup a server instance of seqplots on my machine, for the people in my lab to be able to access it.

I setup a shiny server as specified in https://github.com/rstudio/shiny-server
The shiny server seems to work fine 
![shiny](https://cloud.githubusercontent.com/assets/4232772/21136160/c56dbd1e-c124-11e6-9bbb-0a65704de069.png)

I installed Seqplots:
`sudo su -`
`R`
`source("http://bioconductor.org/biocLite.R")`
`biocLite("seqplots")`

I tried to follow the instructions in:
http://przemol.github.io/seqplots/#installation---server-deployment
`sudo su -`
`R`
`library(seqplots)`
`cp -r $(Rscript -e "cat(system.file('seqplots', package='seqplots'))") /srv/shiny-server/`

But:
`seqplots(root='/var/shiny-server/DATA')`
returns
Error: could not find function "seqplots"

At this stage, the seqplots app cannot be loaded properly and the browser displays:
![seqplots](https://cloud.githubusercontent.com/assets/4232772/21136478/18ec8686-c126-11e6-9e3b-f0067d1d2b12.png)

Running locally the web app seems to work fine:
As normal user
`R`
`library(seqplots)`
`run()`
![ok_seqplots](https://cloud.githubusercontent.com/assets/4232772/21136685/dd6c8b8c-c126-11e6-98ff-a1b9b7d2ed29.png)

Could you give me a hand with this issue ?

Thanks for the great work !

Etienne

**Comment by Przemol** [comment]
Make sure you install seqplots as root user:

```
sudo su
whoami # should return "root"

R

if (!require("devtools")) install.packages("devtools")
devtools::install_github('przemol/seqplots', build_vignettes=FALSE)
```

This should solve the problem.
