### ISSUE TITLE
Error in uploading wig files

### ISSUE THREAD

**Issue by bahreinia** [Przemol/seqplots#23]
Hi,
I get the following error when I try to upload my wig files. 

`Processing file: T47D-WT-V_treat_afterfiting_all.wig.gz [8d488f145e4007b7ab315a9d]
Error in .Call(get("BWGFile_fromWIG", environment(wigToBigWig)), x, seqlengths(gnm),  : 
  Incorrect number of arguments (3), expecting 4 for 'BWGFile_fromWIG'`

I thought maybe my wig file is not in format but it's according to the UCSC accepted format. Here is the first ten line if that:
`track type=wiggle_0 name="T47D-WT-V_treat_all" description="Extended tag pileup from MACS version 1.4.2 20120305 for every 10 bp"
variableStep chrom=chr1 span=10
10021   1
10031   1
10041   1
10051   2
10061   3
10071   3
10081   3
10091   7`

I would appreciate if you could guide me how I can fix this.
Thanks

**Comment by Przemol** [comment]
This issue should be fixed now. 
If you still experience the problem let me know - I'll re-open it.
