### ISSUE TITLE
Error in ...stacktraceon..({ : could not find function "dbConnect"

### ISSUE THREAD

**Issue by jurgjn** [Przemol/seqplots#24]
SeqPlots-3.0.12.dmg on OS X 10.11.6 installs fine, but shows the attached error message on startup.

![seqplots_startup](https://cloud.githubusercontent.com/assets/5638655/23552510/3cb33fc4-0014-11e7-924b-3074f1c74bc7.png)

**Comment by Przemol** [comment]
Please try the latest version:
https://github.com/Przemol/seqplots_electron/releases/download/untagged-9e028e120b269f1f740e/SeqPlots-3.0.15-mac.zip
