### ISSUE TITLE
scaling data on profiles

### ISSUE THREAD

**Issue by descostesn** [Przemol/seqplots#25]
Hi,
I would need to scale the y-axis between 0 and 1 on the profiles (modifying the values not just changing the scale).

Is there a way to modify the data? Or could you provide an option for this?

Thank you very much.

**Comment by Przemol** [comment]
You should set up "Set Y-axis limits" option you have to use for profile plots:
![image](https://user-images.githubusercontent.com/910537/45511505-1bd8c000-b795-11e8-8582-10b72d83f832.png)

For heatmaps key go with "Set default color key limits" option:
![image](https://user-images.githubusercontent.com/910537/45511576-4b87c800-b795-11e8-890b-50fad50b9ff2.png)
