### ISSUE TITLE
Seqplot error

### ISSUE THREAD

**Issue by amitpande74** [Przemol/seqplots#27]
Hi,
I have Ubuntu 14.04 and installed Seqplots according to the instructions mentioned here:
https://github.com/Przemol/seqplots_electron/releases/tag/v3.0.11.
When I run the file it stops after loading and nothing happens.
The developer tools sections shows this error:
stderr: /tmp/.mount_59BLjw/usr/bin/resources/app/Rlinux/lib64/R/bin/exec/R: error while loading shared libraries: libicuuc.so.55: cannot open shared object file: No such file or directory
There are no libraries by that name for ubuntu 14.04.
Kindly help.

**Comment by Przemol** [comment]
Ubuntu 14.04 is not supported, only Ubuntu 16.04 LTS.
You can install R (https://www.r-project.org/) and from R run following code:

```
source("http://bioconductor.org/biocLite.R")
biocLite("seqplots")

if (!require("devtools")) install.packages("devtools")
devtools::install_github('przemol/seqplots', build_vignettes=FALSE)

library(seqplots)
run()
```

This method gives you the same functionality as stand-alone app and work across all Linux distributions.

**Comment by Przemol** [comment]
Try to reinstall SeqPlots with following command:

```
if (!require("devtools")) install.packages("devtools")
devtools::install_github('przemol/seqplots', build_vignettes=FALSE)
```

Please let me know if you still experience problems, I'll re-open this issue.
