### ISSUE TITLE
how to install a self-forged genome

### ISSUE THREAD

**Issue by lifengJGI** [Przemol/seqplots#29]
I tried to load the self-forged genome to the SeqPlots by "install from file". But it didn't show up on the installed genome even I copied whole forged genome folder to the genome folder under SeqPlots. I would appreciate you can give a bit more details on how to install a forged genome from local file. Thanks.

**Comment by Przemol** [comment]
SeqPlots support geneoes in FASTA format now, it's much more straight forward than forging a genome package. Just upload FASTA here:

![image](https://user-images.githubusercontent.com/910537/45512065-90f8c500-b796-11e8-948b-48ad01048c17.png)
