### ISSUE TITLE
Asking for advise: how to normalize different samples before plotting?

### ISSUE THREAD

**Issue by ktrns** [Przemol/seqplots#31]
![seqplots_2datasets_1geneset](https://user-images.githubusercontent.com/9417927/29662342-492add20-88c7-11e7-866e-dc86876365d5.jpg)

Hi, 

I am using seqplots to generate aggregate plots. However, different samples are sequenced to different depths. For example, sample1 contains 4x as many reads as sample2. However, in the plot it seems as if it was 2x as many reads. If I normalize the samples by RPM, sample1 even appears to have a lower signal than sample2, even though they are replicates and should overlap. Do you have any comments or ideas on how to normalize sequencing data before subjecting them to seqplots?

Many thanks in advance,
Katrin

**Comment by Przemol** [comment]
For CHIP-seq experiments I recommend rBEADS:
https://github.com/Przemol/rbeads
