### ISSUE TITLE
Issues with loading genome and .wig

### ISSUE THREAD

**Issue by libri1** [Przemol/seqplots#34]
Hello, I met Julie at the CSH meeting recently and she told me about Seqplots - I just started using it and I have some issues. We would like to analyze strand specific RNA pol II data generated by the CRAC method, which generates (rather large) .wig files. 
I tried to add one of our tracks, using the option "custom" for the genome, but this did not work, and I got the following message:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/31736584/30187574-8145e510-942a-11e7-963e-2a008c089c58.png">
Then I thought that this was due to not having the genome added, so I loaded SacCer3, but again it did not work and I got this message:
<img width="398" alt="image" src="https://user-images.githubusercontent.com/31736584/30187743-3869930e-942b-11e7-9348-7a8a24f1da49.png">
Still, my wig file contains the same numbering for the chromosomes, here is the beginning of the file:
<img width="477" alt="image" src="https://user-images.githubusercontent.com/31736584/30187861-d460b274-942b-11e7-90f3-6d28c0fcb443.png">
It looks like the program has trouble converting the wig to bigwig and this relates to problems with the genome. As a final assay I tried to load our genome, we have it as a .genome package or fasta, but neither appeared as an available genome (the file appeared uploaded, but did not install).
Any suggestion on how to solve these problems ?

Thank you very much
Domenico Libri

**Comment by Przemol** [comment]
The conversion should work current version.

In rare case SeqPlots is unable to convert WIG to BW.
If your conversion stil fails, please use  "wigToBigWig" program from UCSC:
https://www.encodeproject.org/software/wigtobigwig/

BW files are the default format for SeqPlots.
