### ISSUE TITLE
ERROR: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by mtokuyama** [Przemol/seqplots#35]
Hello, 

I'm trying to upload a bed file for a feature, but I keep getting this error: "ERROR: $ operator is invalid for atomic vectors." What am I doing wrong? My bed file looks like this: 

chr | start | end | name
chr1 | 101499079 | 101506294 | 5983
chr1 | 101597412 | 101603403 | 5985
chr1 | 102086135 | 102092888 | 5986
chr1 | 102735637 | 102747998 | 5987
chr1 | 102833368 | 102841125 | 5988
chr1 | 103268225 | 103273353 | 5991
chr1 | 103649080 | 103655071 | 5992
chr1 | 103698053 | 103701660 | 5994
chr1 | 103743218 | 103749209 | 5993
chr1 | 104380123 | 104388639 | 5996
chr1 | 104459780 | 104468289 | 5997
chr1 | 104597438 | 104603785 | 5998
chr1 | 105109274 | 105118215 | 5999
chr1 | 108473135 | 108480383 | 6005
chr1 | 109702615 | 109710648 | 6007

Please help. Thanks! Maria

**Comment by Przemol** [comment]
Try to reinstall SeqPlots with following command:


```
if (!require("devtools")) install.packages("devtools")
devtools::install_github('przemol/seqplots', build_vignettes=FALSE)
```

Please let me know if you still experience problems, I'll re-open this issue.
