### ISSUE TITLE
Cannot select clusters to plot in heatmaps

### ISSUE THREAD

**Issue by DimKat** [Przemol/seqplots#38]
Hello,

After generating heatmaps with the clustering I prefer and turning Make cluster calculation repeatable ON when I try to select specific clusters to be plotted I only get the All clusters option. Then reasonably if I try to download cluster information I get the ERROR: Plot heatmap with clusters or ordering first! 

I have tried with features files uploaded both as .gff or .bed and signal tracks uploaded as bedgraph.

I am using the latest version of Seqplots 3.0.13 on Windows 7 (64-bit) but I had the same issue with 3.0.12.

Any help would be greatly appreciated.

Kind regards,

Dimitris

**Comment by Przemol** [comment]
Thanks for reporting this bug.
Fixed in cf9e0c3de82678847a3ad61429f449850dc9e5d8
