### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by amitpande74** [Przemol/seqplots#41]
Hi,

Whenever I run seqplots I am getting an error message 
Error in ctx$onInvalidate(function() { : 
  Reactive context was created in one process and accessed from another

Can you help.
regards,
Amit

**Comment by Przemol** [comment]
The source of error is well explained here:
rstudio/shiny#2163

I switched SeqPlots to use single process for all calculations.
If time allows I will implement a new way to support for multi-process calculations with "future" package.
