### ISSUE TITLE
fatal error in wrapper code

### ISSUE THREAD

**Issue by passdan** [Przemol/seqplots#42]
I am getting this error during every run of "New plot set" but I can't work out the meaning behind it.

Seqplots v1.10.6 stanalone on Ubuntu 16.04 LTS

**Comment by Przemol** [comment]
Please try installing from R:

```
if (!require("devtools")) install.packages("devtools")
devtools::install_github('przemol/seqplots', build_vignettes=FALSE)
```

Let me know if it works, if not I'll re-open the issue.
