### ISSUE TITLE
Problem launching app OSX 10.13.5

### ISSUE THREAD

**Issue by madhanicode** [Przemol/seqplots#45]
seqplots failed to launch.  received following error:

PROGRESS:15
Loading required package: DBI
Loading required package: methods
Error in sqliteSendQuery(con, statement, bind.data) : 
  error in statement: no such table: files
In addition: Warning message:
In strptime(x, fmt, tz = "GMT") :
  unknown timezone 'zone/tz/2018c.1.0/zoneinfo/America/Los_Angeles'

**Comment by MichaelMW** [comment]
Same here

##########################
Loading application...
PROGRESS:10
Copying demo files and genomes...
PROGRESS:15
Loading required package: DBI
Loading required package: methods
Error in sqliteSendQuery(con, statement, bind.data) : 
  error in statement: no such table: files
In addition: Warning message:
In strptime(x, fmt, tz = "GMT") :
  unknown timezone 'zone/tz/2018e.1.0/zoneinfo/America/Los_Angeles'
################################

**Comment by Przemol** [comment]
Please run following code from R:

```
library(DBI)
library(RSQLite)

root = file.path(path.expand("~"), "SeqPlots_data")

dir.create(root)
setwd(root)

sqlite <- RSQLite::SQLite()
con <- dbConnect(sqlite, dbname = 'files.sqlite')
if ( !length(dbListTables(con)) ) {
    dbGetQuery(con, paste(
        'CREATE TABLE files (id INTEGER PRIMARY KEY ASC, name TEXT UNIQUE,',
        'ctime TEXT, type TEXT, format TEXT, genome TEXT, user TEXT,',
        'comment TEXT)'
    ))
    if ( !length(dbListTables(con)) ) warning('Database not created!')
}
dbDisconnect(con)

if (!all(sapply(
    c('removedFiles','files','publicFiles', 'tmp', 'genomes'), dir.create
))) warning('Folders not created!')
```

This should fix the problem. If you got any warning herer make sure that folder `~/SeqPlots_data` exist and that R process can write files to it.
