### ISSUE TITLE
What is the best way to convert bam files into bigwig or bedgraph to use in seqplots?

### ISSUE THREAD

**Issue by ramonvidal** [Przemol/seqplots#5]
Dear Author,
What is the best way? I dont want to create a binned file (I want the maximum resolution). Which tool do you usually use for converting bam files to one of the required in seqplots?
Thanks

**Comment by Przemol** [comment]
From Bioconductor packages I recommend using [GenomicAlignments package](http://bioconductor.org/packages/release/bioc/html/GenomicAlignments.html) to import BAM file to R and [rtracklayer package](http://bioconductor.org/packages/release/bioc/html/rtracklayer.html) for exporting the reads coverage to BigWig format. This will give you single base resolution track. 

The following R code will do the trick:
```{.R}
library(GenomicAlignments)
library(rtracklayer)

bamfile <- system.file("extdata", "ex1.bam", package="Rsamtools", mustWork=TRUE)
show(bamfile)

alignment <- readGAlignments(bamfile)
reads_coverage <- coverage(alignment)

export.bw(reads_coverage, con = "output_BigWig.bw")
```

Alternatively, you can use command line utilities, for example [bedtools genomecov with -ibam option](http://bedtools.readthedocs.org/en/latest/content/tools/genomecov.html) followed by [wigToBigWig program](http://genome.ucsc.edu/goldenpath/help/bigWig.html)
