### ISSUE TITLE
Seqplots window GUI is greyed-out and non-functional

### ISSUE THREAD

**Issue by c-guzman** [Przemol/seqplots#9]
I managed to install seqplots onto my Fedora machine, and run it, but as soon as the seqplot window opens up in Chrome it greys out and is un-clickable. I can not add any files and have to shut it down manually in R.

**Comment by Przemol** [comment]
Hi, thanks for feedback. Are you running Bioconductor version of SeqPlots? If this is the case try newest development version by running following code in R:
```
if (!require("devtools")) install.packages("devtools")
devtools::install_github('przemol/seqplots', build_vignettes=FALSE)
```
If you still have this problem please send me your `sessionInfo()` after loading seqplots package and info about your web browser.
Best wishes!

**Comment by c-guzman** [comment]
Hey Przemol, thanks for the quick response.

Development version of SeqPlots ended up solving the issue. Thanks!
